# [env]
# TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 12
